version: '3.3'

services:
   db:
     image: mariadb:10.11
     volumes:
       - dbvol:/var/lib/mysql

     environment:
       MYSQL_ROOT_PASSWORD: pastefy
       MYSQL_DATABASE: pastefy
       MYSQL_USER: pastefy
       MYSQL_PASSWORD: pastefy

   pastefy:
     restart: always
     depends_on:
       - db
     image: interaapps/pastefy:latest
     ports:
       - "80:80"
       
     environment:
       HTTP_SERVER_PORT: 80
       HTTP_SERVER_CORS: "*"
       DATABASE_DRIVER: mysql
       DATABASE_NAME: pastefy
       DATABASE_USER: pastefy
       DATABASE_PASSWORD: pastefy
       DATABASE_HOST: db
       DATABASE_PORT: 3306
       SERVER_NAME: "https://snippets.ollaris.org"
       # There is INTERAAPPS, GOOGLE, GITHUB, DISCORD, TWITCH
       OAUTH2_PROVIDER_CLIENT_ID:
       OAUTH2_PROVIDER_CLIENT_SECRET:

volumes:
  dbvol: